model:
  checkpoint: model.cpt
  dt: 0.05
  niter: 4
  hidden_dims: 128
  std: 0.7
  integrator: leapfrog
  n_types: 20 
  energy:
    d_model: 320
    ff_dim: 1280
    n_heads: 20
    n_layers: 6
training:
  num_epochs: 650
  dataset:
    file: dataset.h5
    batch_size: 30
  train_log:
    file: train_log.out
  eval_log:
    file: eval_log.out
  optim:
    lr: 1e-4
    betas: [0.9, 0.95]
    weight_decay: 0.01
    warmup_epochs: 5
